name: check

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Lint spell
        run: pnpm lint:spell

      - name: Lint es
        run: pnpm lint:es

      - name: Lint ts
        run: pnpm lint:ts

      - name: Test
        run: pnpm test
